# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: paypal.me/riipandi
custom: karyakarsa.com/aris
custom: www.buymeacoffee.com/ars
# patreon: riipandi
open_collective: # Replace with a single Open Collective username
